# yaml-language-server: $schema=https://json.schemastore.org/dependabot-2.0

version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
      day: "tuesday"
    commit-message:
      prefix: "ci"
    labels:
      - "bot"
      - "dependencies"
