name: Formatting

on:
  schedule:
    - cron: "40 5 * * 5"
  workflow_dispatch:

jobs:
  do_format:
    uses: ./.github/workflows/format_inc.yml
    with:
      gitref: ${{ github.ref }}
      pull_request: true
    permissions:
      contents: write
      pull-requests: write
