name: Automated Push/PR Check

on:
  push:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.rst'
      - 'LICENSE'
      - '.*'
      - '!.github/**'
    branches:
      - 'main'
  pull_request:
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '**.rst'
      - 'LICENSE'
      - '.*'
      - '!.github/**'

jobs:
  all_checks:
    uses: ./.github/workflows/full_check_inc.yml
    with:
      gitref: ${{ github.ref }}
