name: (Reuse) Tox test

on:
  workflow_call:
    inputs:
      gitref:
        required: true
        type: string
      os:
        required: false
        type: string
        default: 'ubuntu-24.04'
      pyver:
        required: false
        type: string
        default: '3.11'

jobs:
  pytest:
    name: pytest ${{ inputs.pyver }}/${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v4
      with:
        ref: ${{ inputs.gitref }}

    - uses: astral-sh/setup-uv@v5
      with:
        version: '0.6.2'
        python-version: ${{ inputs.pyver }}
        cache-dependency-glob: |
          ./pyproject.toml

    - name: Test suite
      run: >
        uvx
        --python-preference only-managed
        --with tox-gh-actions==3.2.0
        --with tox-uv==1.25.0
        tox@4.24.1 run
