name: (Reuse) Tox test

on:
  workflow_call:
    inputs:
      gitref:
        required: true
        type: string
      os:
        required: true
        type: string
      pyver:
        required: true
        type: string
      tox-uv:
        required: true
        type: string

jobs:
  pytest:
    name: pytest ${{ inputs.pyver }}/${{ inputs.os }}
    runs-on: ${{ inputs.os }}
    steps:
    - uses: actions/checkout@v5
      with:
        ref: ${{ inputs.gitref }}

    - uses: astral-sh/setup-uv@v7
      with:
        version: '0.6.2'
        python-version: ${{ inputs.pyver }}
        cache-dependency-glob: |
          ./pyproject.toml

    - name: Test suite
      run: >
        uvx
        -p ${{ inputs.pyver }}
        --python-preference only-managed
        --with tox-gh-actions==3.2.0
        --with tox-uv==${{ inputs.tox-uv }}
        tox@4.24.1 run
